name: Deploy to Codeberg Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Codeberg Pages
    runs-on: codeberg-small
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # pin@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: |
          npm ci
      - name: Build website
        run: |
          npm run build
      - uses: https://codeberg.org/git-pages/action@v2
        with:
          site: 'https://${{ forge.repository_owner }}.codeberg.page'
          token: ${{ forge.token }}
          source: dist/
      - name: Clear CDN cache
        run: |
          curl -X POST -H "Authorization: ${{ secrets.CACHE_TOKEN }}" https://cache-clear-webhook-bnoi8.bunny.run/ -v
