name: Deploy to Codeberg Pages

on:
  push:
    branches:
      - main
      - lume

jobs:
  deploy:
    name: Deploy to Codeberg Pages
    runs-on: codeberg-small
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6

      - name: Setup Deno
        uses: https://github.com/denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2

      - name: Build website
        run: |
          deno task build
      - name: Deploy to Codeberg Pages
        uses: https://codeberg.org/git-pages/action@v2
        if: github.ref_name == 'main'
        with:
          site: "https://${{ forge.repository_owner }}.codeberg.page/erisa-uk"
          token: ${{ forge.token }}
          source: dist/
      - name: Deploy to Codeberg Pages (Lume)
        uses: https://codeberg.org/git-pages/action@v2
        if: github.ref_name == 'lume'
        with:
          site: "https://${{ forge.repository_owner }}.codeberg.page/erisa-uk/"
          token: ${{ forge.token }}
          source: dist/
          path: lume
      - name: Clear CDN cache
        run: |
          curl -X POST -H "Authorization: ${{ secrets.CACHE_TOKEN }}" https://cache-clear-webhook-bnoi8.bunny.run/ -v
